// Act IV introduces active opposing houses and sustained camp captures.
const ACT4_PATTERNS = [...ACT3_PATTERNS,'rabbits','switch_engine','lidka'];
CAMPAIGN_ACTS.push({id:4,roman:'IV',name:'Der rote Sturm',headline:'Der Himmel brennt.',subtitle:'Halte den Weg nach Norden offen.'});
CAMPAIGN_MISSIONS.push(
    {
        id:'A4_M01',act:4,aiSeed:2902596217,title:'Die gebrochene Waffenruhe',region:'Utopia · Südlicher Zugang',kind:'Durchbruch & Abfangen',point:[52,30],ambience:'outpost',voice:'DIE HELLAS-KOMMANDANTIN',quote:'Der Sturm hat die Leitungen geöffnet. Menschen haben die Tore geschlossen.',
        briefing:'Ein roter Sturm legt alte Wasserkanäle frei. Die Zentrale von Tharsis hilft uns, doch ihre nördlichen Garnisonen gehorchen nicht mehr. Gelbe Flora marschiert auf unser Habitat zu. Fange den Angriff ab, erobere das Sperrcamp und halte den Rückweg bis Generation hundertzwölf offen.',
        debriefing:'Das Sperrcamp schweigt. Die Gefangenen glaubten, Hellas wolle ihre Wasserreserven beschlagnahmen. Voss öffnet den Kanal für beide Seiten: „Wir bringen Evakuierungsfähren.“ Doch weiter nördlich hat eine Garnison zwei Pumpen besetzt. Sie droht, den Zufluss zu kappen.',
        hint:'Der gelbe Gleiter zieht nach links unten auf dein Habitat zu. Eine kleine stabile Kolonie kann ihn abfangen. Für den Angriff brauchst du einen unabhängigen Weg zum Camp. Acht Generationen mit mindestens drei eigenen und mehr eigenen als fremden Zellen sichern es; anschließend endet dort die neue Aussaat.',
        patterns:ACT4_PATTERNS,reward:null,rounds:5,steps:120,budget:22,enemy:true,enemies:[{house:3,budget:24,strength:'hard'}],
        objective:{type:'captureCamps',zones:['fort'],hold:8,minGenerations:112,label:'Tharsis-Camp erobern und eigenes Habitat bis Generation 112 schützen'},
        bonuses:[{type:'generations',value:112,label:'Beim ersten Evakuierungsfenster abschließen'},{type:'spent',value:18,label:'Höchstens 18 Genmaterial einsetzen'}],
        map:{rows:40,cols:60,territory:[[0,3,3,12,16],[0,10,16,19,28],[0,22,4,26,11],[3,27,28,36,44]],rocks:[[0,39,15,40],[28,16,39,17]],camps:[{id:0,rMin:22,rMax:25,cMin:6,cMax:10},{id:3,rMin:24,rMax:30,cMin:24,cMax:30}],seeds:[{pattern:'glider',r:1,c:34,owner:4,mirror:true}],zones:[{id:'fort',house:3,label:'THARSIS · SPERRCAMP',rMin:24,rMax:30,cMin:24,cMax:30}]}
    },
    {
        id:'A4_M02',act:4,aiSeed:4204215417,title:'Die Zangenstellung',region:'Utopia · Besetzte Wasserader',kind:'Doppelte Belagerung',point:[65,40],ambience:'canyon',voice:'UNSERE BIOLOGIN',quote:'Ein Camp fällt. Das andere sät weiter.',
        briefing:'Zwei Tharsis-Camps kontrollieren die Wasserader. Jedes schützt die Versorgung des anderen. Wir müssen beide erobern, bevor die Garnison den Kanal überflutet. Teile deinen Angriff auf. Solange auch nur ein Camp übrig bleibt, wächst ihre gelbe Front weiter.',
        debriefing:'Beide Camps sind gesichert. Unter den Pumpen liegt ein offener Wartungsschacht; Wildwuchs strömt in die Wasserader. Die Besatzer wollten ihn mit immer mehr eigener Flora verdrängen. Jetzt treffen die Fronten aufeinander. Zwei Rettungsplätze liegen dazwischen.',
        hint:'Die beiden Camps liegen auf verschiedenen diagonalen Flugbahnen. Felsfenster begrenzen den Zugang. Sichere jeden Standort acht Generationen gegen Gegenwuchs. Erst wenn beide Camps fallen, verliert Tharsis seine weitere Aussaat. Reagiere zwischen den Evolutionsphasen auf neue Kolonien.',
        patterns:ACT4_PATTERNS,reward:null,rounds:6,steps:250,budget:26,enemy:true,enemies:[{house:3,budget:24,strength:'hard'}],
        objective:{type:'captureCamps',zones:['west','east'],hold:8,label:'Beide Tharsis-Camps erobern; eigenes Habitat erhalten'},
        bonuses:[{type:'rounds',value:3,label:'Beide Camps bis Runde 3 sichern'},{type:'spent',value:22,label:'Höchstens 22 Genmaterial einsetzen'}],
        map:{rows:44,cols:72,territory:[[0,3,3,12,37],[3,29,23,40,57]],rocks:[[0,18,12,19],[24,18,43,19],[0,40,12,41],[24,40,43,41]],camps:[{id:0,rMin:3,rMax:5,cMin:4,cMax:7},{id:3,rMin:24,rMax:30,cMin:24,cMax:30},{id:3,rMin:24,rMax:30,cMin:44,cMax:50}],zones:[{id:'west',house:3,label:'THARSIS · WESTCAMP',rMin:24,rMax:30,cMin:24,cMax:30},{id:'east',house:3,label:'THARSIS · OSTCAMP',rMin:24,rMax:30,cMin:44,cMax:50}]}
    },
    {
        id:'A4_M03',act:4,aiSeed:2255644569,title:'Zwischen den Fronten',region:'Utopia · Umkämpfte Rettungsplätze',kind:'Zweifronten-Verteidigung',point:[56,53],ambience:'outpost',voice:'DIE HELLAS-KOMMANDANTIN',quote:'Wir verteidigen keine Flagge. Wir verteidigen die Fähren.',
        briefing:'Viridion, das Haus der grünen Kolonien, fordert die nördlichen Wasserwege für sich. Seine Truppen kämpfen gegen Tharsis – mitten durch unsere Evakuierung. Schütze beide Rettungsplätze hundertsechzig Generationen vor jeder fremden Flora. Beide Gegner säen nach jeder Runde erneut. Ein einziger Durchbruch beendet die Rettung.',
        debriefing:'Die letzte Fähre verlässt den Sturm. Familien aller drei Häuser sitzen an Bord. Viridion hört ihre Stimmen und bietet einen Korridor an. Doch zwei Kommandoposten kämpfen weiter. Wir müssen ihre Aussaat stoppen, bevor sie die geretteten Wasserwege wieder verbinden.',
        hint:'Zwei mobile Startfronten bedrohen getrennte Landeplätze. Fange beide ab und bewahre Reservekolonien. Nach jeder Runde erhalten die beiden Gegner neues Material aus ihrem Gebiet. Kontrolliere deshalb auch die neu entstehenden Fronten; die ersten beiden Gleiter sind nur der Anfang.',
        patterns:ACT4_PATTERNS,reward:null,rounds:5,steps:48,budget:24,enemy:true,enemies:[{house:2,budget:18,strength:'hard'},{house:3,budget:20,strength:'hard'}],
        objective:{type:'evacuate',value:160,protect:['west','east'],label:'Beide Rettungsplätze 160 Generationen gegen Viridion und Tharsis schützen'},
        bonuses:[{type:'spent',value:20,label:'Höchstens 20 Genmaterial einsetzen'},{type:'population',value:40,label:'Während der Evolution höchstens 40 eigene lebende Zellen gleichzeitig'}],
        map:{rows:50,cols:72,territory:[[0,10,16,19,28],[0,26,40,35,52],[3,3,43,10,54],[2,24,57,33,68]],rocks:[[0,3,7,6],[42,49,49,52]],camps:[{id:0,rMin:18,rMax:19,cMin:26,cMax:28},{id:3,rMin:4,rMax:6,cMin:47,cMax:50},{id:2,rMin:28,rMax:30,cMin:63,cMax:66}],seeds:[{pattern:'glider',r:1,c:34,owner:4,mirror:true},{pattern:'glider',r:17,c:58,owner:3,mirror:true}],zones:[{id:'west',label:'RETTUNG WEST',rMin:22,rMax:27,cMin:6,cMax:13},{id:'east',label:'RETTUNG OST',rMin:38,rMax:43,cMin:30,cMax:37}]}
    },
    {
        id:'A4_M04',act:4,aiSeed:4204215417,title:'Die letzte Gegenoffensive',region:'Utopia · Zwei Kommandoposten',kind:'Angriff unter Schutzauftrag',point:[38,62],ambience:'research',voice:'UNSERE BIOLOGIN',quote:'Jeder eroberte Posten nimmt eine Front aus dem Kampf.',
        briefing:'Ein grüner und ein gelber Kommandoposten verweigern die Waffenruhe. Erobere beide, während unsere Zivilstation im Süden geschützt bleibt. Jeder gefallene Posten stoppt die neue Aussaat seines Hauses. Vorhandene Kolonien verschwinden dadurch nicht. Halte die Station bis Generation hundertachtundzwanzig frei von fremder Flora.',
        debriefing:'Die beiden Kommandoposten geben auf. Ihre Karten zeigen die eigentliche Gefahr: Drei letzte Garnisonen verteidigen den Sturmspeicher. Wenn ihre Kolonien zusammenwachsen, versagt die Trennung der Wasseradern. Voss fordert alle Häuser auf, ihre Evakuierungsrouten offenzulegen. Diesmal antworten sie.',
        hint:'Plane zwei Angriffswege und einen getrennten Abfangpunkt für den gelben Gleiter. Eroberte Camps bleiben gesichert; konzentriere dich danach auf den noch aktiven Gegner. Die Zivilstation muss auch nach dem letzten Campfall bis zum Ende des Rückzugs geschützt bleiben.',
        patterns:ACT4_PATTERNS,reward:'glider_gun',rounds:6,steps:32,budget:30,enemy:true,enemies:[{house:2,budget:22,strength:'hard'},{house:3,budget:24,strength:'hard'}],
        objective:{type:'captureCamps',zones:['west','east'],hold:8,minGenerations:128,protect:['civilians'],label:'Beide Kommandoposten erobern und Zivilstation bis Generation 128 schützen'},
        bonuses:[{type:'generations',value:128,label:'Beim ersten Rückzugsfenster abschließen'},{type:'spent',value:24,label:'Höchstens 24 Genmaterial einsetzen'}],
        map:{rows:44,cols:72,territory:[[0,3,3,12,37],[0,10,24,19,36],[3,29,24,39,35],[2,29,44,39,57]],rocks:[[0,40,10,41],[30,38,43,39]],camps:[{id:0,rMin:3,rMax:5,cMin:4,cMax:7},{id:3,rMin:24,rMax:30,cMin:24,cMax:30},{id:2,rMin:24,rMax:30,cMin:44,cMax:50}],seeds:[{pattern:'glider',r:1,c:34,owner:4,mirror:true}],zones:[{id:'west',house:3,label:'THARSIS · KOMMANDO',rMin:24,rMax:30,cMin:24,cMax:30},{id:'east',house:2,label:'VIRIDION · KOMMANDO',rMin:24,rMax:30,cMin:44,cMax:50},{id:'civilians',label:'ZIVILSTATION',rMin:22,rMax:27,cMin:14,cMax:21}]}
    },
    {
        id:'A4_M05',act:4,aiSeed:3429056601,title:'Das Auge des Sturms',region:'Utopia · Letzte Garnisonen',kind:'Aktfinale · Dreifache Belagerung',point:[49,75],ambience:'canyon',voice:'GEMEINSAMER FUNKKANAL',quote:'Hinter uns liegen die Siedlungen. Vor uns ihre letzte Chance.',
        briefing:'Drei Garnisonen blockieren den Sturmspeicher. Zwei gehören Tharsis, eine Viridion. Erobere alle, während Wildwuchs die Evakuierung bedroht. Der neue Kanonenbauplan ist mächtig, aber teuer und schwer unterzubringen. Entscheide, wo dein Material am meisten bewirkt. Halte den Rettungsplatz bis Generation hundertsechzig offen.',
        debriefing:'Die letzte Garnison schweigt. Zum ersten Mal fließt Wasser durch gemeinsam gewartete Leitungen, während die Pflanzenkolonien getrennt bleiben. Der Sturm zieht weiter. Voss fragt nicht mehr, wem der Mars gehört. Sie fragt, wer morgen Verantwortung übernimmt. Die Häuser müssen jetzt eine gemeinsame Ordnung finden.',
        hint:'Drei Camps benötigen unabhängige Angriffe. Tharsis bleibt aktiv, solange eines seiner beiden Camps steht. Reserviere Material zum Abfangen der grauen Flora links und nutze die kurzen Runden zur Nachsteuerung. Eine Gleiterkanone lohnt sich nur mit freier Schussbahn; sie ist keine Pflichtlösung.',
        patterns:[...ACT4_PATTERNS,'glider_gun'],reward:null,rounds:7,steps:32,budget:44,enemy:true,enemies:[{house:2,budget:16,strength:'hard'},{house:3,budget:16,strength:'hard'}],
        objective:{type:'captureCamps',zones:['west','center','east'],hold:12,minGenerations:160,protect:['evac'],label:'Alle drei Garnisonen erobern und Rettungsplatz bis Generation 160 schützen'},
        bonuses:[{type:'generations',value:160,label:'Vor dem letzten Sturmstoß abschließen'},{type:'spent',value:36,label:'Höchstens 36 Genmaterial einsetzen'}],
        map:{rows:50,cols:88,territory:[[0,3,3,13,61],[0,10,20,19,32],[3,31,24,43,35],[2,31,44,43,55],[3,31,64,43,77]],rocks:[[0,40,12,41],[26,40,49,41],[0,60,12,61],[28,60,49,61]],camps:[{id:0,rMin:3,rMax:5,cMin:4,cMax:7},{id:3,rMin:24,rMax:31,cMin:24,cMax:31},{id:2,rMin:24,rMax:31,cMin:44,cMax:51},{id:3,rMin:24,rMax:31,cMin:64,cMax:71}],seeds:[{pattern:'glider',r:1,c:38,owner:-1,mirror:true}],zones:[{id:'west',house:3,label:'THARSIS · WEST',rMin:24,rMax:31,cMin:24,cMax:31},{id:'center',house:2,label:'VIRIDION · ZENTRUM',rMin:24,rMax:31,cMin:44,cMax:51},{id:'east',house:3,label:'THARSIS · OST',rMin:24,rMax:31,cMin:64,cMax:71},{id:'evac',label:'RETTUNGSPLATZ',rMin:22,rMax:27,cMin:10,cMax:17}]}
    }
);
CAMPAIGN_MISSIONS.filter(m => m.act === 4).forEach(m => { m.narration = 'recorded'; m.audioRevision = '20260914-v1'; });
