// Act V turns the skirmish-scale systems into a sustained, planet-wide campaign.
const ACT5_PATTERNS = [...ACT4_PATTERNS, 'glider_gun'];
CAMPAIGN_ACTS.push({id:5,roman:'V',name:'Das geteilte Netz',headline:'Der Mars braucht kein Zentrum.',subtitle:'Er braucht eine Ordnung, die morgen noch hält.'});
CAMPAIGN_MISSIONS.push(
    {
        id:'A5_M01',act:5,aiSeed:1511094273,title:'Tausend rote Morgen',region:'Arcadia · Westliche Fernleitung',kind:'Langzeitfront · Doppelte Belagerung',point:[29,27],ambience:'canyon',voice:'DIE HELLAS-KOMMANDANTIN',quote:'Ein Sieg hält eine Stunde. Eine Versorgungslinie muss Jahre halten.',
        briefing:'Das gerettete Olympus-Netz erreicht Arcadia, doch zwei verlassene Tharsis-Relais speisen weiter unkontrollierte Kolonien. Erobere beide Stationen und halte das westliche Habitat über zweitausend Generationen. Jede Evolutionsphase dauert tausend Generationen; zwischen den Phasen kannst du die gewachsene Landschaft neu beurteilen und verstärken.',
        debriefing:'Nach zweitausend Generationen fließt die erste Fernleitung stabil. In den Relais finden wir keinen Sabotagebefehl, sondern automatische Notfallpläne: Jede Station sollte allein überleben. Gemeinsam erzeugen sie jedoch eine Front. Viridion meldet drei Habitate, die genau zwischen solchen Plänen liegen.',
        hint:'Die Felsrücken teilen das Hochland in drei breite Korridore. Schicke getrennte Angriffe zu beiden Relais und halte eine stabile Reserve beim Habitat. Die langen Evolutionsphasen bestrafen ungebremste Methusalems; nutze die nächste Runde, um auf die tatsächlich entstandenen Trümmerfelder zu reagieren.',
        patterns:ACT5_PATTERNS,reward:null,rounds:5,steps:1000,budget:90,budgetFactor:18,radius:7,enemy:true,enemies:[{house:3,budget:54,strength:'hard'}],
        objective:{type:'captureCamps',zones:['relayNorth','relaySouth'],hold:24,minGenerations:2000,protect:['habitat'],label:'Beide Fernrelais erobern und das Habitat 2.000 Generationen schützen'},
        bonuses:[{type:'rounds',value:2,label:'Nach genau zwei Evolutionsphasen stabilisieren'},{type:'spent',value:72,label:'Höchstens 72 Genmaterial einsetzen'}],
        map:{rows:72,cols:112,territory:[[0,27,5,44,25],[0,54,8,66,31],[3,8,78,22,105],[3,48,82,66,105]],rocks:[[0,36,20,38],[31,36,71,38],[0,72,40,74],[54,72,71,74],[25,48,28,65],[43,48,46,65]],camps:[{id:0,rMin:30,rMax:36,cMin:8,cMax:15},{id:3,rMin:10,rMax:18,cMin:88,cMax:98},{id:3,rMin:52,rMax:60,cMin:88,cMax:98}],seeds:[{pattern:'acorn',r:13,c:70,owner:4},{pattern:'switch_engine',r:49,c:73,owner:4}],zones:[{id:'relayNorth',house:3,label:'FERNRELAIS NORD',rMin:10,rMax:18,cMin:88,cMax:98},{id:'relaySouth',house:3,label:'FERNRELAIS SÜD',rMin:52,rMax:60,cMin:88,cMax:98},{id:'habitat',label:'ARCADIA-HABITAT',rMin:29,rMax:39,cMin:4,cMax:18}]}
    },
    {
        id:'A5_M02',act:5,aiSeed:309584117,title:'Drei Lichter im Krater',region:'Amazonis · Habitatsenke',kind:'Langzeitfront · Dreifache Verteidigung',point:[43,38],ambience:'outpost',voice:'VIRIDION-KOORDINATION',quote:'Autonomie bedeutet nicht, dass jede Siedlung allein sterben muss.',
        briefing:'Drei Habitate liegen in einer alten Einschlagssenke. Grüne und gelbe Notfallflora dringt durch getrennte Kratertore ein, während die Bewohner ihre lokalen Genome sichern. Halte alle drei Siedlungen dreitausend Generationen frei. Beide Häuser säen nach jeder tausendsten Generation nach; deine Front muss sich über mehrere Runden anpassen.',
        debriefing:'Drei Lichter bleiben an. Viridion öffnet seine Genarchive und erkennt zugleich den Preis völliger Freiheit: Ohne gemeinsame Sperrkorridore hätten die lokalen Varianten einander ausgelöscht. Unter dem Krater verläuft Kesslers älteste Wartungsstraße zum Olympus-Knoten – und ihre biologischen Tore stehen offen.',
        hint:'Die drei Habitate liegen nicht auf derselben Angriffslinie. Baue an jedem Ort eine eigenständige Abfangzone und bewahre bewegliche Reserven in der Mitte. Kontrolliere nach jeder langen Evolution zuerst die neuen Einflussgebiete: Sie bestimmen, wo du in der nächsten Runde überhaupt aussäen kannst.',
        patterns:ACT5_PATTERNS,reward:null,rounds:6,steps:1000,budget:110,budgetFactor:16,radius:8,enemy:true,enemies:[{house:2,budget:42,strength:'hard'},{house:3,budget:42,strength:'hard'}],
        objective:{type:'evacuate',value:3000,protect:['northHab','centerHab','southHab'],label:'Drei Habitate 3.000 Generationen gegen beide Fronten schützen'},
        bonuses:[{type:'generations',value:3000,label:'Alle Habitate im dritten Zeitfenster sichern'},{type:'spent',value:90,label:'Höchstens 90 Genmaterial einsetzen'}],
        map:{rows:84,cols:128,territory:[[0,8,45,20,83],[0,34,50,49,77],[0,63,45,75,83],[2,4,102,20,123],[3,63,102,79,123]],rocks:[[0,29,19,32],[27,29,56,32],[65,29,83,32],[0,92,27,95],[36,92,49,95],[58,92,83,95],[26,58,29,69],[54,58,57,69]],camps:[{id:0,rMin:35,rMax:43,cMin:54,cMax:63},{id:2,rMin:7,rMax:15,cMin:109,cMax:118},{id:3,rMin:68,rMax:76,cMin:109,cMax:118}],seeds:[{pattern:'glider',r:8,c:88,owner:3,mirror:true},{pattern:'glider',r:68,c:88,owner:4,mirror:true},{pattern:'rabbits',r:39,c:100,owner:-1}],zones:[{id:'northHab',label:'HABITAT NORD',rMin:7,rMax:17,cMin:48,cMax:61},{id:'centerHab',label:'HABITAT MITTE',rMin:35,rMax:48,cMin:34,cMax:47},{id:'southHab',label:'HABITAT SÜD',rMin:64,rMax:76,cMin:48,cMax:61}]}
    },
    {
        id:'A5_M03',act:5,aiSeed:2769308641,title:'Die offenen Tore',region:'Olympus · Wartungslabyrinth',kind:'Langzeitfront · Sperrkorridore',point:[54,50],ambience:'research',voice:'UNSERE BIOLOGIN',quote:'Ein Korridor verbindet Menschen. Für die Flora muss er eine Grenze bleiben.',
        briefing:'Kesslers Wartungsstraße verbindet die Habitate, aber drei breite rote Sperrkorridore trennen ihre Pflanzenzonen. Erobere die beiden alten Steuerlager und halte alle Korridore zweitausend Generationen vollständig steril. Grauer Wildwuchs und beide Garnisonen nutzen jede Lücke. Ein einziger lebender Kontakt verbindet das Netz erneut.',
        debriefing:'Die Tore schließen sich, Menschen und Wasser passieren weiter. Kesslers vollständiges Protokoll wird lesbar: PALISADE scheiterte nicht an einem aggressiven Genom, sondern an zentralen Notfallplänen, die gleichzeitig dieselben Grenzen öffneten. Tharsis veröffentlicht daraufhin seine geschönten Risikoberichte. Noch fehlt der Hauptverteiler.',
        hint:'Rot markierte Korridore dürfen von keiner Flora berührt werden, auch nicht von deiner. Kämpfe auf ihrer jeweils sicheren Seite und bevorzuge stabile oder gerichtete Muster. Die Steuerlager müssen 24 Generationen gehalten werden; anschließend bleibt ihre Eroberung gesichert, der Sterilschutz aber bis Generation 2.000 aktiv.',
        patterns:ACT5_PATTERNS,reward:null,rounds:5,steps:1000,budget:100,budgetFactor:18,radius:7,enemy:true,enemies:[{house:2,budget:38,strength:'hard'},{house:3,budget:38,strength:'hard'}],
        objective:{type:'captureCamps',zones:['greenControl','yellowControl'],hold:24,minGenerations:2000,protect:[],sterile:['gateWest','gateCenter','gateEast'],label:'Beide Steuerlager erobern; drei Sperrkorridore 2.000 Generationen steril halten'},
        bonuses:[{type:'rounds',value:2,label:'Im zweiten Langzeitfenster abschließen'},{type:'spent',value:82,label:'Höchstens 82 Genmaterial einsetzen'}],
        map:{rows:80,cols:132,territory:[[0,32,5,47,27],[0,54,6,68,28],[0,8,48,25,66],[0,52,80,70,96],[0,30,108,47,124],[2,8,102,25,126],[3,52,102,70,126]],rocks:[[0,38,21,40],[29,38,79,40],[0,72,31,74],[40,72,79,74],[0,100,18,102],[28,100,48,102],[58,100,79,102]],camps:[{id:0,rMin:35,rMax:43,cMin:8,cMax:17},{id:2,rMin:11,rMax:20,cMin:111,cMax:121},{id:3,rMin:56,rMax:65,cMin:111,cMax:121}],seeds:[{pattern:'acorn',r:25,c:58,owner:-1},{pattern:'diehard',r:47,c:83,owner:-1}],zones:[{id:'greenControl',house:2,label:'VIRIDION · TORSTEUERUNG',rMin:11,rMax:20,cMin:111,cMax:121},{id:'yellowControl',house:3,label:'THARSIS · TORSTEUERUNG',rMin:56,rMax:65,cMin:111,cMax:121},{id:'gateWest',label:'SPERRKORRIDOR WEST',rMin:0,rMax:79,cMin:42,cMax:44},{id:'gateCenter',label:'SPERRKORRIDOR MITTE',rMin:0,rMax:79,cMin:76,cMax:78},{id:'gateEast',label:'SPERRKORRIDOR OST',rMin:0,rMax:79,cMin:104,cMax:106}]}
    },
    {
        id:'A5_M04',act:5,aiSeed:4081187259,title:'Kein Haus allein',region:'Olympus · Planetarer Hauptverteiler',kind:'Langzeitfront · Vier Wege',point:[66,62],ambience:'ice',voice:'GEMEINSAMER FUNKKANAL',quote:'Heute verteidigen wir nicht unsere Farben. Wir verteidigen ihre Abstände.',
        briefing:'Der Hauptverteiler versorgt vier Regionen, doch vier automatische Relais arbeiten gegeneinander. Sichere die grünen und gelben Kontrollstationen, während zwei zivile Verteiler dreitausend Generationen frei bleiben. Die Landschaft ist größer als jede bisherige Front. Nur getrennte Kolonien, Reserven und wiederholte Kurskorrekturen überstehen drei volle Zyklen.',
        debriefing:'Nach dreitausend Generationen bleiben vier regionale Netze stabil und getrennt. Die Häuser übertragen ihre Wartungsschlüssel in ein gemeinsames Protokoll – noch ohne politische Einigung. Im Kern des Verteilers wartet Kesslers letzte Aufzeichnung und eine Entscheidung, die keine Simulation für uns treffen kann.',
        hint:'Behandle die Karte wie vier verbundene Gefechte. Die Kontrollstationen brauchen dauerhafte Mehrheiten, die zivilen Verteiler dagegen Abstand zu jeder fremden Flora. Gib nicht dein gesamtes Material in Runde eins aus: Nach tausend Generationen ist die neue Topologie wichtiger als der ursprüngliche Plan.',
        patterns:ACT5_PATTERNS,reward:null,rounds:6,steps:1000,budget:130,budgetFactor:15,radius:8,enemy:true,enemies:[{house:2,budget:48,strength:'hard'},{house:3,budget:48,strength:'hard'}],
        objective:{type:'captureCamps',zones:['viridionKey','tharsisKey'],hold:32,minGenerations:3000,protect:['northDistributor','southDistributor'],label:'Beide Kontrollstationen erobern und zwei Verteiler 3.000 Generationen schützen'},
        bonuses:[{type:'rounds',value:3,label:'Nach drei Evolutionsphasen synchronisieren'},{type:'spent',value:108,label:'Höchstens 108 Genmaterial einsetzen'}],
        map:{rows:92,cols:148,territory:[[0,39,5,54,29],[0,39,37,54,61],[0,39,69,54,93],[2,6,116,23,141],[3,68,116,85,141]],rocks:[[0,34,31,36],[43,34,91,36],[0,68,20,70],[31,68,60,70],[71,68,91,70],[0,104,34,106],[46,104,91,106],[27,78,30,96],[61,78,64,96]],camps:[{id:0,rMin:40,rMax:50,cMin:8,cMax:18},{id:2,rMin:9,rMax:19,cMin:125,cMax:136},{id:3,rMin:72,rMax:82,cMin:125,cMax:136}],seeds:[{pattern:'switch_engine',r:7,c:98,owner:3},{pattern:'rabbits',r:72,c:98,owner:4},{pattern:'lidka',r:36,c:108,owner:-1}],zones:[{id:'viridionKey',house:2,label:'VIRIDION · SCHLÜSSEL',rMin:9,rMax:19,cMin:125,cMax:136},{id:'tharsisKey',house:3,label:'THARSIS · SCHLÜSSEL',rMin:72,rMax:82,cMin:125,cMax:136},{id:'northDistributor',label:'VERTEILER NORD',rMin:10,rMax:23,cMin:45,cMax:59},{id:'southDistributor',label:'VERTEILER SÜD',rMin:68,rMax:81,cMin:45,cMax:59}]}
    },
    {
        id:'A5_M05',act:5,aiSeed:1984247195,title:'Das Gedächtnis des Bodens',region:'Olympus · Kern des Netzes',kind:'Finale · Planetare Langzeitordnung',point:[50,76],ambience:'research',voice:'DR. ADA KESSLER · LETZTE AUFZEICHNUNG',quote:'Die Flora erinnert sich an nichts. Aber jede Generation erbt die Folgen der vorherigen.',
        briefing:'Im Kern laufen alle Fehler des alten Netzes zusammen. Sichere drei regionale Knoten, halte die gemeinsame Schutzzone frei und bewahre unser Habitat über viertausend Generationen. Vier lange Evolutionsphasen zeigen, ob die Ordnung wirklich trägt. Danach entscheiden die Siedlungen, wem Wartung, Archive und Genome anvertraut werden.',
        debriefing:'Viertausend Generationen. Drei getrennte Pflanzenzonen. Im Schutzraum stehen vier cyanfarbene Zellen als stiller Block – dieselbe Form wie bei der Landung. Kesslers Stimme endet: „Das ist genug.“ Der Mars ist nicht gerettet, aber seine Siedlungen besitzen jetzt eine Ordnung, die sie gemeinsam weitertragen können.',
        hint:'Das Finale ist ein vollständiges Gefecht, kein einzelnes Musterpuzzle. Teile Angriff, Schutz und Reserve auf drei Fronten. Der rote Ring muss immer leer bleiben. Prüfe nach jeder tausendsten Generation Einflussgebiet, gegnerische Nachsaat und offene Flugbahnen, bevor du die nächste Phase auslöst.',
        patterns:ACT5_PATTERNS,reward:null,rounds:7,steps:1000,budget:150,budgetFactor:14,radius:9,enemy:true,enemies:[{house:2,budget:52,strength:'hard'},{house:3,budget:52,strength:'hard'}],
        objective:{type:'captureCamps',zones:['northNode','centerNode','southNode'],hold:32,minGenerations:4000,protect:['habitat'],sterile:['commonSeal'],label:'Drei Netzknoten sichern; Habitat und Schutzzone 4.000 Generationen bewahren'},
        bonuses:[{type:'rounds',value:4,label:'Nach vier Evolutionsphasen vollenden'},{type:'spent',value:124,label:'Höchstens 124 Genmaterial einsetzen'}],
        finalChoices:[{id:'consortium',title:'Gemeinsames Mars-Konsortium',text:'Wasserquoten und Wartung werden gemeinsam kontrolliert. Die Häuser geben einen Teil ihrer Hoheit ab, erhalten dafür verbindliche gegenseitige Hilfe.'},{id:'open_genomes',title:'Freie lokale Genome',text:'Die PALISADE-Archive werden veröffentlicht. Lokale Anpassung bleibt frei, während ein gemeinsamer Vertrag die Sperrkorridore schützt.'}],
        map:{rows:96,cols:160,territory:[[0,40,5,57,31],[0,40,38,57,63],[0,40,70,57,96],[0,7,82,25,99],[0,40,82,57,99],[0,70,82,88,99],[2,7,126,25,153],[3,70,126,88,153]],rocks:[[0,35,29,37],[45,35,95,37],[0,67,19,69],[30,67,65,69],[76,67,95,69],[0,101,31,103],[43,101,63,103],[75,101,95,103],[28,79,31,91],[64,79,67,91]],camps:[{id:0,rMin:43,rMax:53,cMin:8,cMax:19},{id:2,rMin:10,rMax:20,cMin:135,cMax:146},{id:3,rMin:42,rMax:52,cMin:135,cMax:146},{id:2,rMin:74,rMax:84,cMin:135,cMax:146}],seeds:[{pattern:'acorn',r:12,c:118,owner:3},{pattern:'rabbits',r:43,c:118,owner:4},{pattern:'switch_engine',r:76,c:118,owner:3},{pattern:'lidka',r:39,c:105,owner:-1}],zones:[{id:'northNode',house:2,label:'NETZKNOTEN NORD',rMin:10,rMax:20,cMin:135,cMax:146},{id:'centerNode',house:3,label:'NETZKNOTEN MITTE',rMin:42,rMax:52,cMin:135,cMax:146},{id:'southNode',house:2,label:'NETZKNOTEN SÜD',rMin:74,rMax:84,cMin:135,cMax:146},{id:'habitat',label:'OLYMPUS-HABITAT',rMin:42,rMax:55,cMin:5,cMax:21},{id:'commonSeal',label:'GEMEINSAME SCHUTZZONE',rMin:31,rMax:66,cMin:73,cMax:76}]}
    }
);
// Staging islands beyond the sterile corridors let players fight on each separated side
// without ever having to grow through a protected strip.
CAMPAIGN_MISSIONS.find(m => m.id === 'A5_M03').map.territory.push([0,8,108,25,110],[0,52,108,70,110]);
CAMPAIGN_MISSIONS.find(m => m.id === 'A5_M05').map.territory.push([0,7,108,25,123],[0,40,108,57,123],[0,70,108,88,123]);
CAMPAIGN_MISSIONS.filter(m => m.act === 5).forEach(m => { m.narration = 'recorded'; m.audioRevision = '20260915-v1'; });
